format = """
$directory\
$kubernetes\
$helm\
$opa\
$docker_context\
$git_branch\
$git_status\
$rust\
$bun\
$deno\
$golang\
$java\
$kotlin\
$terraform\
$package\
$sudo\
[](fg:bg_colour)\
$fill\
[](fg:bg_colour)\
$status\
$cmd_duration\
$jobs\
$time\
\n$character"""

palette = 'nord'

[palettes.nord]
bg_colour = '#3B4252'
text_colour = '#D8DEE9'
character_bg_colour = '#D8DEE9'
character_text_colour = '#2E3440'
character_text_error_colour = '#BF616A'

[fill]
symbol = ' '

[character]
success_symbol = "[❯](fg:character_bg_colour)"
error_symbol = "[❯](fg:character_text_error_colour)"

# Left modules

[directory]
format = "[ $path ]($style)"
style = "bg:bg_colour"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = "󰊢"
style = "bg:bg_colour"
format = '[｜ $symbol $branch ]($style)'

[git_status]
style = "bg:bg_colour"
format = '[($all_status$ahead_behind )]($style)'

[bun]
symbol = ""
style = "bg:bg_colour"
format = '[｜ $symbol ($version) ]($style)'

[nodejs]
symbol = "󰎙"
style = "bg:bg_colour"
format = '[｜ $symbol ($version) ]($style)'

[rust]
symbol = "󱘗"
style = "bg:bg_colour"
format = '[｜ $symbol ($version) ]($style)'

[golang]
symbol = "󰟓"
style = "bg:bg_colour"
format = '[｜ $symbol ($version) ]($style)'

[package]
style = "bg:bg_colour"
format = '[｜ 󰏗 $version ]($style)'

# Right modules

[cmd_duration]
min_time = 500
style = "bg:bg_colour"
format = '[ took  $duration ｜]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:bg_colour"
format = '[  $time ]($style)'

