### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk

# Binary paths (set early so tool integrations can find binaries)
typeset -U path
path+=$HOME/.local/bin
path+=$HOME/.bun/bin
path+=$HOME/.cache/.bun/bin
path+=$HOME/.cargo/bin
path+=$HOME/.yarn/bin
path+=$HOME/.krew/bin
path+=$HOME/.proto/bin
export PATH

# Environment
export PROTO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/proto"
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock
export DOCKER_SOCK=$XDG_RUNTIME_DIR/podman/podman.sock
export EDITOR=nvim

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# Zsh Plugins
zinit light zsh-users/zsh-autosuggestions
zinit wait lucid for \
    zsh-users/zsh-syntax-highlighting

# Load completions - zsh-completions must load before compinit
zinit ice blockf
zinit light zsh-users/zsh-completions

# Custom completions (generated by `gencomps`)
fpath=($HOME/.local/share/zsh/completions $fpath)

# Cache compinit - skip security check when dump exists
autoload -Uz compinit bashcompinit
if [[ -f "${ZDOTDIR:-$HOME}/.zcompdump" ]]; then
    compinit -C
else
    compinit
fi
bashcompinit

# gcloud completions (requires bashcompinit, can't be pre-generated)
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

# fzf-tab must load after compinit
zinit light Aloxaf/fzf-tab

# kubectl plugin completions - intercept "kubectl <plugin>" and delegate
# to the plugin's own completion (e.g. kubectl-cnpg __complete ...)
_kubectl_plugin_completer() {
    local -a plugins=(cnpg)
    if (( CURRENT >= 3 )) && (( ${plugins[(Ie)${words[2]}]} )); then
        local plugin=${words[2]}
        words=(kubectl-${plugin} "${words[@]:2}")
        (( CURRENT-- ))
        autoload -Uz +X _kubectl-${plugin} 2>/dev/null
        _kubectl-${plugin}
    else
        _kubectl "$@"
    fi
}
compdef _kubectl_plugin_completer kubectl k

# History
HISTSIZE=10000
HISTFILE=$HOME/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_find_no_dups

setopt AUTO_CD              # Type a directory name to 'cd' into it without typing 'cd'
setopt GLOB_DOTS            # Include hidden files in completions/wildcards
setopt INTERACTIVE_COMMENTS # Allow pasting commands with comments directly into the shell

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# Cached eval helper - regenerates when the binary changes
_cached_eval() {
    local name=$1; shift
    local cache_file="$HOME/.cache/zsh/${name}.zsh"
    local bin_path="${commands[$1]}"
    if [[ ! -f "$cache_file" ]] || [[ -n "$bin_path" && "$bin_path" -nt "$cache_file" ]]; then
        mkdir -p "$HOME/.cache/zsh"
        "$@" > "$cache_file"
    fi
    source "$cache_file"
}

# Starship Prompt
_cached_eval starship starship init zsh

# Integrations
_cached_eval fzf fzf --zsh
_cached_eval zoxide zoxide init --cmd cd zsh
_cached_eval direnv direnv hook zsh
_cached_eval fnm fnm env --use-on-cd
_cached_eval proto proto activate zsh

autoload -Uz up-line-or-beginning-search
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[3~" delete-char

# Aliases
alias k="kubectl"
alias j="just"
alias ls="eza -lah --icons --git --group-directories-first"
alias tree="eza --tree --icons"

# Regenerate tool completions (run after installing/upgrading tools)
gencomps() {
    local dir="$HOME/.local/share/zsh/completions"
    mkdir -p "$dir"
    kubectl completion zsh > "$dir/_kubectl"
    kubectl cnpg completion zsh > "$dir/_kubectl-cnpg"
    bun completions > "$dir/_bun"
    rm -f "${ZDOTDIR:-$HOME}/.zcompdump"
    echo "Completions regenerated. Restart shell to pick up changes."
}
